nanoframework/nf-debugger

UWP/Debug Library/Extensions/OutputExtensions.cs, UWP/Debug Library/NFDevice/NanoDeviceBase.cs, UWP/Debug Library/WireProtocol/Commands.cs
=> Correct structure for flash map command

UWP/Debug Library/Properties/AssemblyInfo.cs, UWP/NuGet.nanoFramework Debug Library/NuGet.nanoFramework Debug Library.nuproj
- bumped version number to v0.2.20
- released Nuget package
=> Version update

UWP/Debug Library/CLRCapabilities.cs, UWP/Debug Library/MFDeployTool/NanoFrameworkDeviceInfo.cs, UWP/Debug Library/WireProtocol/Commands.cs, UWP/Debug Library/WireProtocol/Converter.cs, UWP/Debug Library/WireProtocol/Engine.cs
=> Rename solutioninfo to targetinfo

source/nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Net/app.config, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.1.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/DebuggerEventSource.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/EventHandlerForUsbDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Converter.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Request.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- improve separation of UWP and .NET
- comment debug.writeline (isn't available in .NET)
- bumped Nuget to 0.3.0-preview002
-
=> Further work on debug library

source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
=> Bumped Nuget version to 0.4.0-preview008

source/Serial Test App UWP/MainPage.xaml, source/Serial Test App UWP/MainPage.xaml.cs
=> Add test to debugger extension

appveyor.yml, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
=> Bumped version to 0.4.0-preview009

source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- bumped Nuget package to 0.4.0-preview011
=> Add field to expose flags as enum

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_String.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- supports nanoframework/nf-interpreter/#361
=> Add error code to reply of access memory commands

source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Request.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- this is not following the async recommended coding
- bumped Nuget version to 0.4.0-preview014
=> Remove ConfigureAwait from calls

source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- move word aligment to check to begining of method
- improve progress report (WIP)
- correct bug with deployment part (was relying on the assembly list to deploy instead of the block list)
- minor code format improvements
- bump Nuget version to 0.4.0-preview015
=> Improve code in Deploy incremental method

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
- improve code that fills in the device description
- add extra delay on open device to allow slower systems to settle
=> Fixed issues with device add/removal

appveyor.yml, source/nanoFramework.Tools.DebugLibrary.Net/Properties/AssemblyInfo.cs, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.UWP/Properties/AssemblyInfo.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- libraries to 0.5
- Nuget packages to 0.4.0-preview018
=> Bump versions

appveyor.yml
- temporary fix for AppVeyor connection issues to Nuget (TO BE REVERTED)
=> Temporary work around for Nuget connection issues

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/MonitorFlashSectorMapExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- add new table with region total size
- improve formating
- replace old code with a couple new extensions to improve reuse and readability
=> Improvements in flash map output

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs
- replace fixed index with selected index from data grid
- add test code for device reboot
- correct typo
=> Improvements in test app

appveyor.yml, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
=> Bump version to 0.4.0-preview019

appveyor.yml, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Request.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- code improvements on reboot command
- fixes #35
- bump Nuget packages version to 0.4.0-preview020
=> Fix issue with Reboot command

appveyor.yml, source/Serial Test App UWP/project.json, source/USB Test App UWP/project.json, source/USB Test App WPF/Serial Test App WPF.csproj, source/USB Test App WPF/packages.config, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Net/packages.config, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj, source/nanoFramework.Tools.DebugLibrary.UWP/project.json
=> Update Nuget packages

appveyor.yml, source/USB Test App WPF/packages.config, source/nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- allows output of image build date and compiler version
- bump Nuget packages to 0.4.0-preview023
- Closes nanoFramework/Home#230
Checked output on test app.
=> Exposed compiler details for device capabilities

.github_changelog_generator, CHANGELOG.md, GitVersion.yml, appveyor.yml, source/nanoFramework.Tools.DebugLibrary.Net/GitVersion.yml, source/nanoFramework.Tools.DebugLibrary.Net/Properties/AssemblyInfo.cs, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.UWP/Properties/AssemblyInfo.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
Add scripts and configurations to auto generate version and changelog on release.
=> Work on automated versioning and changelog

GitVersion.yml, appveyor.yml
- Have different AppVeyor configs according to branch.
- Update GitVersion branch configs.
- Applies CI and version configs according to latest project policy.
=> Update CI config files

GitVersion.yml, appveyor.yml
- Update CI config to publish NuGet packages on PR.
- This makes it super easy to test NuGet packages before merging a PR.
=> Update CI config to publish NuGet on PRs

appveyor.yml
- Add GitHub publish for development branch.
- This enhancement allows setting up a GitHub release draft making it easy to publish preview versions.
=> Add GitHub publish for development branch

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add extra code to always transmit data packets with at least 64 bytes.
+semver: fix
- Resolves major issue of not being able to deploy an app when the assembly blob size had the last packet shorter than 64 bytes.
- Deployment successful for various apps in VS experimental instance.
=> Correct WriteMemoryAsync

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/USB Test App WPF/Serial Test App WPF.csproj, source/USB Test App WPF/packages.config
- Add more commands and variations to improve test app
- Improves test options .
=> Update WPF test app

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Rename fields.
- Improve handling of disconnection after reboot command.
=> Rework MonitorReboot

source/nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs
- Moved IsDevicesEnumerationComplete to PortBase
- Makes property access more convenient.
=> Moved IsDevicesEnumerationComplete

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Fix declaration of `Monitor_Message`
=> Fix declaration of Monitor_Message

source/nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Removed related methods and calls
- Update code accordingly
- Not used
=> Remove LCDCapabilities

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/PingConnectionType.cs
- Rename `PingConnectionType` for coherence
=> Rename PingConnectionType for coherence

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
- Refactor `operationTimeout` in `ProcessAsync` to ease reuse on calls bellow
- Fix `CompletePayload` code that wasn't forwarding unexpected messages
- Fix `ProcessMessage` that wasn't correctly validating the reply when it was originated by a request
- Code clean-up
- Remove `Debug.WriteLine` as those are not required anymore
- Fixes potential issues with Wire Protocol message processing when there are unsolicited messages being sent from the target device.
=> Work on MessageReassembler

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Net/BinaryFormatter.cs, source/nanoFramework.Tools.DebugLibrary.Net/BitStream.cs, source/nanoFramework.Tools.DebugLibrary.Net/EndPoint.cs, source/nanoFramework.Tools.DebugLibrary.Net/Exceptions/RemotedException.cs, source/nanoFramework.Tools.DebugLibrary.Net/Message.cs, source/nanoFramework.Tools.DebugLibrary.Net/MessageCall.cs, source/nanoFramework.Tools.DebugLibrary.Net/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IControllerHostLocal.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IControllerRemote.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Request.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems, source/nanoFramework.Tools.DebugLibrary.UWP/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- Improvements in MessageReassembler
- Work on `Engine.ProcessMessageAsync`
- Work on Engine to start adding support for VS debugging session
- Add several new classes to add support for VS debugging session
- Several improvements in WPF test app
- Clean-up `Debug.Writeline` not required anymore
=> Work on Wire Protocol and VS debugging support

source/Serial Test App UWP/MainPage.xaml, source/Serial Test App UWP/MainPage.xaml.cs, source/USB Test App UWP/MainPage.xaml.cs, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/EventHandlerForSerialDevice.cs
- Further improvements in connect/disconnect workflow for SerialPort
- Clean-up and polish `Engine` code
- Increase timeout of `DiscoverCLRCapabilityAsync`
- Update test apps
- Improves stability of component
=> Improve connection/disconnection from SerialDevice

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/TaskExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Improve workflow of GetAppDomainsAsync and GetAssembliesAsync to catch invalid replies from device
- Fixes issues in getting assemblies from device
=> Fix GetDeviceInfo

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
- Moved task that gets spurious chars to `Start` so it's not eating CPU when idle
- Currently this task is not doing anything useful 
=> Improvements in debug engine

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/SerialPort.cs
- Attempt to solve the exceptions thrown when performing R/W operation with serial port
=> Complete rework on SerialPort send and receive methods

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
=> Fix potential issue with output stream on SendBufferAsync

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
=> Fix semaphore in PerformRequestAsync

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/EngineState.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Add engine state
- Work on Engine to add events, rework properties and methods to manage start, stop, resume
- Code clean up
- Improvements required for VS extension
=> Work on engine start/stop

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs
- Result was being checked against the wrong flag.
=> Fix IsDeviceInInitializeStateAsync

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs
- Add IsDeviceInExitedStateAsync extension.
- Required for VS debugger.
=> Add IsDeviceInExitedStateAsync

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs
- Fix DebuggerExtensions
- Comparison was wrong
=> Fix DebuggerExtensions

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Rename tupple object (for clarity)
- Also correct typos
=> Rename tuple object (for clarity)

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
- Rework command to use enums instead of constants
- Rework GetExecutionModeAsync()
- Add SetExecutionModeAsync()
- Rework extensions accordingly
- Rework test apps
=> Work on DebuggingExecutionChangeConditions command

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Drop Start method on Engine, it now starts all the required tasks
- Change Engine constructor to remove unnecessary parameter
- Engine is NOT instantiated anymore when NanoDevice object is created
- Update WPF test app
=> Work on Engine

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
- Correct namespace on WireProtocolRequest
=> Correct namespace on WireProtocolRequest

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
=> MessageReassembler Process is now an async Task

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Attempt to improve handling of exceptions on waiting task
=> Improve Convert to handle exceptions on waiting task

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs
- The transport definition was missing for serial devices
=> Add missing transport definition

source/nanoFramework.Tools.DebugLibrary.Net/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
- Add timeout to WireProtocolRequest
=> Add timeout to WireProtocolRequest

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Converter.cs
- Improve fields deserializer
- Simplified attribute name
=> Improve fields deserializer

source/Serial Test App UWP/MainPage.xaml.cs, source/USB Test App UWP/MainPage.xaml.cs, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/EndPoint.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Message.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RunTimeValue.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Array.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_ByRef.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Class.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Indirect.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Primitive.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_String.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IControllerHostLocal.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
- Rework async methods for debug engine
- Rework test apps accordingly
- The use of async methods isn't not compatible with the CorDebug synchronous nature
=> Rework async methods for debug engine

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Command event is now invoked on a new Task
=> Command event is now invoked on a new Task

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- GetStackFrameValueAll now returns a List
=> GetStackFrameValueAll now returns a List

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/IncomingMessageExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IncomingMessage.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Add IncomingMessageExtensions
- Remove equivalent method in the IncomingMessage class
- Update code accordingly
=> Add IncomingMessageExtensions

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Now checks for null reply
- Now returns false execution on failure
=> Improve WriteMemory

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
=> Fix return from WriteMemory

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Uncomment code to output proper string
- Fixes nanoFramework/Home#253
=> Fix Monitor_Message ToString()

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Improve debugger message decoding
- Safely ignore non-ascii chars and return a string in all situations
- Suggested by @MikroBusNet  [here](https://github.com/nanoframework/nf-debugger/pull/105#issuecomment-350805929)
=> Improve debugger message decoding

source/USB Test App WPF/FodyWeavers.xml, source/USB Test App WPF/Serial Test App WPF.csproj, source/USB Test App WPF/Serial Test App WPF.previous.nugetreferenceswitcher, source/USB Test App WPF/ViewModel/MainViewModel.cs, source/USB Test App WPF/packages.config, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Net/packages.config, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- Update code and Fody definitions to match last changes
- Add config file to use Nuget reference switcher extension
-  Making it easier to test PR packages
=> Update several Nuget packages

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Improve code in PerformSyncRequest methods
- Adjust packet size for WriteMemory
- Remove some ConfigureAwait that wheren't doing much
- Update test app to mimic a real deployment scenario
- Fixes deployment issues for deployment blobs on which the remainder package was smaller than 64 bytes.
- WPF test app (updated specifically to test this issue)
=> Work on sync requests

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Now closes unused serial devices that are not nF devices
- Addresses nanoframework/Home/issues#276
=> Now closes unused serial devices that are not nF devices

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs
- Add code to output info about config block
=> Add code to output info about config block

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Correct ReadMemory return value (was always returning a 0 length array)
=> Correct ReadMemory return value

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/AddressMode.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfigurationBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/NetworkConfigurationBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Add classes to hold device configuration and network configuration
- Add methods to Engine and commands to get configuration
- Add method to Engine to write configuration to device
- Add code to WPF app to test all the above
- Provide API to R/W configuration from/to device
- Using the WPF test app
- Double check flash content with ST-Link
=> Add methods to read/write configuration block

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add code to check for error code at WriteMemory command
- Fixes/Closes/Resolves nanoFramework/Home#297
=> Add code to check for error code at WriteMemory command

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add alternative method to save partial config updates
- Update test code
=> Add alternative method to save partial config updates

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs
=> Fix IP address parsing

source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfigurationBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/NetworkWireless80211ConfigurationBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/NetworkWireless80211ConfigurationPropertiesBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Add code to allow a specific config block to be addressed
- Update  code of config update operation
- Rename NetworkWireless to NetworkWireless80211
- Required improvements on debugger lib
- {x] All new and existing tests passed.
=> Work on configration management

source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfigurationOption.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DeviceConfigurationExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Fix IsUnknown properties
- Fix bug with GetAllNetworkConfigurations and GetAllNetworkWirelessConfigurations
- Add extensions for DeviceConfiguration
- Rename some commands fields for brevity
- Rename some enums for clarity
=> Work on device configuration

source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/NetworkConfigurationBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/NetworkConfigurationPropertiesBase.cs
- Add dynamic DNS property to netwok config block
=> Add dynamic DNS property to netwok config block

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
- Add device to list of troublesome USB devices
- Addresses nanoframework/Home#332
- Test is only possible on a machine with this device. Waiting for @trabuzin to provide feedback.
=> Add device to list of troublesome USB devices

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/EngineState.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
Reverts nanoframework/nf-debugger#145
=> Revert "Improvements in engine process exit and termination"

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add check for engin running on engine connectasync
- Improve code related with calls to ProcessExit on device failure
- Improve code in engine IncomingMessagesListenerAsync
- Engine is not stoped anymore on SeriaPort device disconect
- Add missing exception in UsbDevice
- Update WPF test app
- [ x] I have read the **CONTRIBUTING** document.
=> Improvements in engine process exit and termination

source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs
- Improves access to property as it's available right after a successful connection to a target without any other queries
=> Improve getter of NativeAssemblies

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Improve the checks on connect async to make sure that device capabilities are always reported back from device, otherwise can't proceed
- Add check for proper reply from device on DiscoveryInteropNativeAssemblies, failure is not an option
- Addresses nanoframework/Home#342
=> Improvements on deployment

source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Rework GetAssemblies() which now returns an empty collection instead of null
- Improve code in ResolveAllAssemblies()
=> Improvements in assemblies resolving

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
- Was being overwritten on device enumeration after the initial one
=> Fix issue with SerialDevice description

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Need to be able to disconnect device without knowing it's type (Serial or USB)
=> Move device disconnect to NanoDeviceBase

source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs
- Add line breaks before each section
- Replace string format with interpolated strings
- Remove unused usings
=> Improve output of ToString for NanoFrameworkDeviceInfo

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Reported by @MatthiasJentsch (thanks 👏  )
=> Fix bug in Engine.ProcessMessage

source/Serial Test App UWP/MainPage.xaml.cs, source/USB Test App UWP/MainPage.xaml.cs, source/USB Test App WPF/MainWindow.xaml.cs, source/USB Test App WPF/ViewModel/MainViewModel.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NanoDevicesEventSource.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/EventHandlerForUsbDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/EventHandlerForSerialDevice.cs
- update test app accordingly
- correct several typos along the way
- Addresses nanoFramework/Home#356
=> Add logging to nano device events (arrival, departure, checking)

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Addresses nanoFramework/Home#362
=> Add support for configurable Wire Protocol packet size

source/nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs
- Addresses nanoFramework/Home#358
=> Add suport for capability flag reporting if target has nanoBooter

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Fixes wrong max buffer size check
=> Fix issue with WP buffer length

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Also update test app
- Addresses nanoFramework/Home#366
=> Improve code to validate deployment before actually commiting it

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
- Closes nanoFramework/Home#332
=> Add new device ID to black list

source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/EraseOptions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Update EraseAsync code
- Fixes nanoFramework/Home#375
=> Add new erase option for configuration block

source/USB Test App WPF/App.config, source/USB Test App WPF/App.xaml.cs, source/USB Test App WPF/Serial Test App WPF.csproj, source/USB Test App WPF/ViewModel/MainViewModel.cs, source/USB Test App WPF/ViewModel/ViewModelLocator.cs, source/USB Test App WPF/packages.config, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Net/packages.config, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
=> Update all Nugets to latest versions

source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/AuthenticationType.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/EncryptionType.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/NetworkInterfaceType.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/RadioType.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Having this makes it much easier to work the bindings and presentation layer
=> Add Display.Description atrribute to network enums

.github_changelog_generator, appveyor.yml, commit-assemblyinfo-changes.ps1, generate-change-log.ps1
=> Work on CI & CD

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
- Add new entries to Serial Devices black list.
- Improve black listed devices in hope of get rid of device discovery issues.
=> Add new entries to Serial Devices black list

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/RebootOptions.cs
- This reboot option is not required anymore as CLR is now capable of properly rebooting.
- Following nanoframework/nf-interpreter#1183.
=> Remove NoShutdown from RebootOptions

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs
- Add header block for flash, memory and usage outputs.
- Tweak alignments.
- Remove it from the test app.
=> Tidy output of device capabilites listings

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
-  UpdateDeviceConfiguration now follows  device properties regarding the need (or not) to erase config block before updating.
- Despite the device properties declaring that the configuration does not require erase, the code was ignoring that and undergoing through the get and update workflow. This improves that behaviour.
=> Fix update network config

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs
- Helps debugging the device state by outputting it in a human readable format.
Signed-off-by: José Simões<jose.simoes@eclo.solutions>
=> Add output to help debug device state

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add output of error codes on WriteMemory.
- Need to provide better insight to the caller on what went wrong. Outputting the error codes returned by the device was due.
=> Add output of error codes on WriteMemory

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add new method UpdateDebugFlags.
- Part of the debug session launch workflow is setting the appropriate flags on the target debugger engine at some point. The current approach was to call ConnectAsync, operation on which those flags are set. It happens that the ConnectAsync performs A LOT of other operations (managing the VS debugger engine, calling the low level connect API, querying device capabilities, etc). All these are not only unnecessary at this step but have the potential to wreck the debugger engine and the low level connection and stress the device CLR with a lot of unnecessary chat on the receiver thread. Adding this simple method that perform exactly what's required at that step is much more efficient and logical. 
=> Add new method UpdateDebugFlags

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Change progress output on foreach iteration.
- Moved progress output after the foreach on completion.
- The progress report output was wrong as it was repeatedly writing what was supposed to be outputted after the operation completed.
=> Fix progress output on DeploymentExecuteIncremental

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Return of DebugEngine.EraseMemory wasn't being properly checked.
- Minor code improvements.
- Addresses nanoFramework/Home#465.
=> Improve code on EraseAsync

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Improve initial code sequence in EraseAsync. Now the forced connection to target device is only performed if the device is not responsive.
- Remove unnecessary workflow and save time on this operation.
=> Improvements in EraseAsync

source/nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/ReleaseInfo.cs, source/version.json
- Add new properties to ReleaseInfo.
- Update helper methods and callers accordingly.
- Add these to NanoFrameworkDeviceInfo class and ToString() output.
- Add these to TargetInfoProperties.
- Rename TargetInfoProperties properties for clarity.
- Bump version to 1.2.0-preview.
- Addresses nanoFramework/Home#414.
- Test app on solution.
=> Add target name and platform name properties

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Fix deployment progress message
- Fixes nanoFramework/Home#500
Signed-off-by: MateuszKlatecki <mateusz.klatecki@gc5.pl>
=> Fix deployment progress message

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- IsConnected flag is now updated on Ping.
- IsConnected flag is now lowered on RebootDevice only when appropriate.
- Resolves connection and reconnection issues that showed after increasing the WP baud rate.
=> Improvements in deployment

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/version.json
- Fix command implementation.
- Update test application with test call to this one.
- Bump version to 1.3.1-preview.
- Test app on Solution.
=> Fix OemInfo command

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs
- Replace chars in ToString output on device capabilities.
- So they don't produce markup formatting which messes up with GitHub issues, for example.
=> Replace chars in ToString output on device capabilities

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/ReleaseInfo.cs
- Add code to properly parse the raw value and return valid strings (data only up to the terminator char).
- The properties value included all garbage returned from native call.
=> Fix getters of ReleaseInfo class

source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add try-catch statements.
- Add catch all to several methods.
- General stability improvements.
=> Work towards stability improvement

source/nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs
- Add BootTime property.
- Set default value to 1500ms.
- Update code to use this instead of hardcoded value.
- Improves flexibility.
=> Expose bootTime property

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs
- Remove second attempt.
- Add random waiting before attempting to communicate with the device to prevent issues with dual USB devices.
- The second attempt to communicate with the device was introduced to improve the detection of ESP32 devices. Turns out that, after careful analysis, that the issue with ESP32 is that on a power on event the MCU is performing a double boot, making it unresponsive until the second boot completes. This behaviour has the effect that the detection algorithm consideres the device irresponsive and thus timeout. This is being investigated and hopefully corrected.
- The "extra" random waiting is to prevent issues with dual USB devices as it seems that reusing the same USB endpoint may cause issues.
Signed-off-by: josesimoes …
=> Improvements on device detection

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/version.json
- Exposing existing method for partial target capabilities.
- Bump version to 1.12.0-preview.
- Needed a way to get the basic target info without having to request all device capabilities.
=> Add new method GetTargetInfo

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, source/version.json
- Move black list check to event handler.
- Add second attempt with boot time plus extra random time wait before second attempt, with device connect.
- Validation of nanoDevice is now using ConnectAsync without device caps and calling GetTargetInfo for names.
- Bump version to 1.14.0-preview.
- Improvements in device detection are paramount to a good user experience.
=> Improve device detection

source/Serial Test App UWP/MainPage.xaml.cs, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/ReleaseInfo.cs, source/version.json
- Add new field PlatformInfo to ReleaseInfo.
- Rework deserialize code to deal with new and old formats.
- Rework GetMonitorOemInfo to return the correct class.
- Update test apps accordingly.
- Bump version to 1.15.0-preview.
- Add support for nanoFramework/nf-interpreter#1570.
-  WPF test app.
=> Update ReleaseInfo and related

source/Serial Test App UWP/MainPage.xaml.cs, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/ReleaseInfo.cs
- Rework ToString implementation of DeviceInfo.
- Add ToString to ReleaseInfo.
- Update test apps accordingly.
- Drop unused or repeated data.
- Provide formatted output of ReleaseInfo for convenience.
=> Update output format of ReleaseInfo and DeviceInfo

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Update AccessMemoryErrorCodes enum.
- Following nanoframework/nf-interpreter#1575.
- Addresses nanoFramework/Home#578.
=> Update AccessMemoryErrorCodes enum

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add break to while loop otherwise a critical failure in the communication would cause the loop to never exit thus causing the update operation to never return.
=> Fix UpdateDeviceConfiguration not returning

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add "Done" field to signal target that the packet is the last one in the sequence.
-Following nanoframework/nf-interpreter#1586
=> Improve UpdateConfiguration command

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add code to retry once on sending the update chunks.
- Takes care of random communication issues without having to perform the complete operation again.
=> Improve update device config

azure-pipelines.yml, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.nuspec, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.nuspec
- Revert to nuspec file.
- Remove all nuspec properties from project files.
- Rework Azure pipeline yaml accordingly.
=> Rework Nuget packages generation

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Fix processing of OemInfo.
- Wasn't handling properly a reply with an empty payload.
=> Fix processing of OemInfo

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Fix declaration of c_Ping_Source_Host.
- Rename and fix handling of PingEvent  event in debugger engine.
- Improvement on reboot detection.
- Addresses nanoFramework/Home#605.
=> Improve reboot handling

source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/Wireless80211_ConfigurationOptions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/WirelessAP_ConfigurationOptions.cs
- Update wireless config enums to follow latest version in System.Net.
=> Update wireless config enums

source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/Wireless80211_ConfigurationOptions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/WirelessAP_ConfigurationOptions.cs
- Add description attribute to some enum items.
- Improves readability of the enums.
=> Improve description on some Wireless config enums

source/USB Test App WPF/App.xaml.cs, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs
- Add new constructors to improve usability.
- Add code to check serial device against COM port black list before openning it.
- Update WPF test app to test this new feature.
- Allow implementation of nanoFramework/Home#635.
=> Add COMPortBlackList to SerialPortManager

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, version.json
- Fix processing of EraseMemory and WriteMemory calls.
- Minor improvements in code style.
- Bump version to 1.18.1-preview.
- The calls to EraseMemory and WriteMemory calls where ignoring the error code and not handling correctly the success/failure of the operation. The information output was wrong and potentially misleading.
- Test app in the project.
=> Fixes in deploy method

nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, nanoFramework.Tools.DebugLibrary.Shared/Capabilities/Stm32.TargetCapabilities.cs
- Update formating of Capability enum.
- Add missing platform and capability flags.
- Correct typo in capability word.
- Rework STM32 capability flags to use enum instead of hard coded value.
- Update code accordingly.
=> Work capability flags

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Fix check for nanoBooter flag.
=> Fix check for nanoBooter flag

Serial Test App UWP/MainPage.xaml.cs, USB Test App UWP/MainPage.xaml.cs, USB Test App WPF/MainWindow.xaml, USB Test App WPF/MainWindow.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/SRecordFile.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, version.json
- Rework PrepareForDeployAsync.
- Rework DeploySrecFileAsync.
- Made DeploySrecFileAsync private because the format parsing is not working.
- Update test apps to use this new method.
- Bump version to 1.21.0-preview.
=> Add DeployBinaryFileAsync to NanoDeviceBase

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Add DeploymentStartAddress and ClrStartAddress to NanoDevice.
- Need to have these readily accessible without requiring constantly performing complex computation to get these.
=> Add DeploymentStartAddress and ClrStartAddress

USB Test App WPF/MainWindow.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, version.json
- Add several target properties that where available only on Engine.
- Improve handling of invalid data in address properties.
- Improve connect to include flash sector map.
- Add test code to app.
- Bump version to 1.22.0-preview.
- Make target capabilities accessible at device level.
- Fixes issues when attempting to retrieve addresses when there is no valid flash sector map.
- Test apps in solution.
=> Improvements in NanoDevice target properties

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, version.json
- Add ConnectionId to NanoDeviceBase.
- Bumps version to 1.23.0-preview.
- Exposes this property  to make it easily available to client code.
- Test apps.
=> Add ConnectionId to NanoDeviceBase

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Remove null check in getter code.
- With those nulls where being returned when there weren't valid data, which is not the intended outcome.
=> Fix access to Version properties in NanoDevice

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Improve formatting. 
- Remove duplicated or not meaningful messages.
=> Improve progress messages during DeployBinaryFileAsync

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
=> Improve message output

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Add VerifyMemory method (WIP).
- Update DeployFile to use this step.
- Required to improve update process robustness.
=> Add VerifyMemory method

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Implement command.
- Improve VerifyMemory in DeployFile to use this new command.
- Needed a method to check memory content on target to be able to verify write operation.
=> Add CheckMemory command to Engine

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add IProgress parameter to WriteMemory methods.
- Improve operation feedback.
=> Add progress report to WriteMemory methods

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Add new property DeviceId to NanoDeviceBase.
- Need to uniquely identify a device. The current approach uses the device description. It's flawed because devices that re-enumerated have the same description and this can cause previous instances from being mistakenly used.
=> Add new property DeviceId

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Fix Polly policy (was using the opposite condition).
=> Fix ConnectAsync

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs
- Fix ID setting.
- Fix baud rate output.
- Increase boot time to 3s.
=> Improve serial device check

Serial Test App UWP/MainPage.xaml.cs, USB Test App UWP/MainPage.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/IPort.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IControllerHostLocal.cs, version.json
- Rework send and read async methods in SerialDevice.
- Finetune ConfigureAwait in async calls.
- Update test apps as required.
- Bump version.
- Improves stability.
=> Rework async methods

nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.nuspec, nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.nuspec
=> Add missing dependencies on nuspec

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add code to process ping reply.
- Improve setting of property on all occasions that connection source might be checked.
- Rename parameter for clarity.
=> Fix setting of ConnectionSource field

nanoFramework.Tools.DebugLibrary.Shared/ArrayEqualityComparer.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Add step to read back programed data for checking (debug mode only).
- Add equality comparer for byte arrays.
- Need to check and debug issues in target flash programming.
=> Improve DeploymentExecuteIncremental

nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs
- Add retry policy to IsDeviceInInitializeState.
- Deal with communication and platform shortcomings by adding a retry policy
=> Add retry policy to IsDeviceInInitializeState

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Add Poly retry policy to Ping.
- Deal with communication and platform shortcomings by adding a retry policy.
=> Add retry policy to Ping

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
=> Fix write memory output

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Rework code to use sectors instead of blocks.
- Decrease time to execute erase memory operation.
=> EraseAsync now uses sectors instead of blocks

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, USB Test App WPF/App.config, USB Test App WPF/App.xaml.cs, USB Test App WPF/MainWindow.xaml.cs, USB Test App WPF/Serial Test App WPF.csproj, azure-pipelines.yml, nanoFramework.Tools.DebugLibrary.Net/app.config, nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, nanoFramework.Tools.DebugLibrary.Net/packages.lock.json, nanoFramework.Tools.DebugLibrary.Shared/DebuggerEventSource.cs, nanoFramework.Tools.DebugLibrary.Shared/Extensions/ConditionsStateExtensions.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/INanoDevice.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoSerialDevice.cs, nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/IPort.cs, nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/PortBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerial.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/EngineState.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/OutgoingMessage.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs, nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Replace UWP libraries with System.Io.SerialPort.
- Improvements in device connection, detection and communication.
- Major rework of Wire Protocol.
- Ditched everything related with UWP.
- Remove most of async calls.
- Rework async and sync communication with device.
- Bump version to 2.0.0.
**REQUIRES CLR v1.6.5.0 or better**
- Moving away from UWP and towards .NET Core (still not possible because of lack of support for .NET Core in VS extensibility).
- Need to improve communication stability with devices connected with serial ports.
- Extensive tests with test app and VS experimental instance.
=> Rework Wire Protocol

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs
Improving device watcher for some Serial Port detection when plugged and unplugged very quickly
- Fixes issues on some serial ports when plugged and unplugged quickly
Tested with the UWP app
=> Improving device watcher

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Device is now disconnected after detection phase.
- IsConnected flag is now updated on engine stop.
- Fixes issues with ESP32 devices detection.
=> Work on serial device detection

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerial.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add calls to Thread.Yield to allow back-off on the serial channel.
- Connect now discards the in buffer if the port is already opened.
- Need to improve in serial comms.
=> Improvements in serial comms

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/INanoDevice.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, nanoFramework.Tools.DebugLibrary.Shared/NanoDevicesEventSource.cs, nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/IPort.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerial.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/ConnectPortResult.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IController.cs, nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Add enum to better report device connection result: ConnectPortResult.
- Update Controller and interfaces with new return value from Connect methods.
- Update Connect method in Engine accordingly.
- Increase reboot timeout to handle slower devices.
- Addresses nanoFramework/Home#755.
=> Improvements in port connection

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
- Idle check is now decreased to 50ms.
- Add code to prevent a request from waiting forever for the controller to be idle.
- Request time stamp is now added even for failed requests, thus allowing the request to be remove from the queue in any event.
- Fix potential infinite wait of WP request.
=> Improve handling of WP request execution

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add code to report success/failure of reboot execution.
- Need to know if the reboot operation was succesful or not.
=> Reboot now returns operation result

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- IsConnected properties now reflect the "master" property IsConnected.
- Add extra delay between calls to update flags.
- Connection source property is now updated on Stop and RebootDevice.
- Improves connection/disconnection workflows.
=> Improvements related with connection

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/TypeSysLookup.cs
- Replace direct access to dictionary with try.
- 
- This has to use try method because the key may not exist.
=> Fix lookup in type system

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Converter.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Rework some code.
- Change vars declaration.
- Improve converter to skip fields added by Foody post build processing.
- Addresses nanoFramework/Home#787.
=> Certificate update to device are now more robust

nanoFramework.Tools.DebugLibrary.Shared/DebuggerEventSource.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
- Add method to log WP payload content.
- Add call to output payload content.
- Need to get insight on the payload content.
=> Add method to log WP payload content

nanoFramework.Tools.DebugLibrary.Shared/PortComposite/PortCompositeDeviceManager.cs, nanoFramework.Tools.DebugLibrary.Shared/PortTcpIp/NetworkWatcher.cs
- Fix call to stop device watcher.
- Rework TCP port start and stop.
- Minor code style improvements.
- Fix issues with network watcher start/stop.
- Improve start and stop of TCP port.
=> Fixes in composite and tcp ports

nanoFramework.Tools.DebugLibrary.Shared/PortComposite/PortCompositeDeviceManager.cs
- Add LogMessageAvailable event to PortComposite.
- This event was missing as no log messages from ports where made available.
=> Add LogMessageAvailable event to PortComposite

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
- Add enum with detection value.
- Rework code accordingly.
- Improve code readability.
=> Rework valid marker detection

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add missing parameter in call to WriteMemory.
- Move progress message to the beginning of the iteration.
- Output proper and complete progress message.
=> Fix output of progress when deploying

USB Test App WPF/App.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Flags.cs, version.json
- Improve parsing of write memory request result.
- Add tiny sleep between write memory operations to account for failures.
- Increase timeout for write operation.
- Add empty flags constant.
- CheckMemory renamed to PerformWriteMemoryCheck.
- Write memory operation check is now performed on release build.
- Fix WPF test app.
- Bump version to 2.1.0-preview.
- Attempt to improve write memory operations in some devices.
=> Improve write memory operation

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Slight increase the pause between requests.
- Attempt to improve communication for some devices/USB serial chips.
=> Increase pause between requests

nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs
- Add missing validation for existing IPAddress when trying to parse those.
- These were causing random issues when updating the network configuration.
=> Fix parsing of network configuration

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Better output with progress and error report.
- Slight increase in slack between write batches to cope with slower targets.
- Code style fixes.
=> Improvements in WriteMemory API

nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj
- Revert DataAnnotations to v6.0
- Need to downgrade other packages in VS extension.
=> Revert DataAnnotations to v6.0

nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj
- Update DataAnnotations NuGet.
- No need to have this referencing v6.0
=> Update DataAnnotations NuGet

nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortComposite/PortCompositeDeviceManager.cs, nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/PortBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs, nanoFramework.Tools.DebugLibrary.Shared/PortTcpIp/PortTcpIpManager.cs
- Add new method AddDevice.
- Add implementation in tcpip port and serial port managers.
- Fix code style per guidelines.
- Need to be able to create nanoDevice without starting device watchers.
=> Add AddDevice method to PortBase

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerial.cs
- Intellisense comments. 
- Initial work in #360 from @Ellerbach, extracted here to separate from PR with real fix.
=> Intellisense comments

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add code to fully erase deployment region instead of just the blocks that are required for deployment.
- Add intellisense comments to DeploymentExecute.
- Code style fixes.
- Fixes nanoFramework/Home#1311.
- Test application
=> Rework DeploymentExecuteIncremental to fully erase deployment region

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Remove unused variable.
- Add missing Intellisense comments.
- Add missing calls to progress report.
- Code style fixes.
- Addresses Skyworks-Timing-Software/MCU/issues/68.
- Tested with nanoff.
=> Improvements in Erase operation

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Total progress now accounts for the correct operation length.
- Fixes progress report not showing any progress on erase and the progres reported was lacking the erase part.
- VS experimental instance.
=> Fix progress report in incremental deployment

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- If device is running nanoBooter performs flash erase per block.
- Improvements on requirement to reboot to nanoBooter.
- Improvement on reboot after erase operation.
- Addresses Skyworks-Timing-Software/MCU#84.
- nanoff test app to perform updates on CLR
=> Rework Erase operation

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Rework computation of progress to accomplish a smoother and accurate progress.
- Fix wrong output of deployment size.
- Show a more smooth and accurate progress of deployment operation.
- Deployment using VS experimental instance for several targets.
=> Fix output progress reporting for deployment operation

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Incremental count is now correctly updated.
- Fixe wrong output progress on certain targets.
- Deploying in VS experimental instance with several targets.
=> Fix output progress on deployment

nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.NetworkConfigurationProperties.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.Wireless80211ConfigurationProperties.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.WirelessAPConfigurationProperties.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.X509CaRootBundleProperties.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.X509DeviceCertificatesProperties.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/NetworkConfigurationPropertiesBase.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/Wireless80211ConfigurationPropertiesBase.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/WirelessAPConfigurationPropertiesBase.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/WirelessConfigurationPropertiesBase.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/X509CaRootBundlePropertiesBase.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/X509DeviceCertificatesPropertiesBase.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Declared assets as private (this is a development dependency).
- Add fody config properties to project.
- Add partial to classes decorated with AddINotifyPropertyChangedInterface so that the code generator can add the necessary event and event-invokers.
- Removes declared dependency of PropertyChanged.Fody.
- Improvements to help Fody code generator.
=> Improvements in PropertyChanged.Fody

nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj
- Migrate target framework to .NET 8.
=> Migrate target framework to .NET 8
