source/USB Test App WPF/App.xaml.cs, source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Net/Properties/AssemblyInfo.cs, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.UWP/Properties/AssemblyInfo.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- DeviceAccessInformation is only available in UWP, therefore calling it was crashing the component, refactor by provinding different implementation for each variant
- fix #14 (only for Serial, still occurs in USB)
- add version and properties to debugger library projects
=> Refactor RegisterForDeviceAccessStatusChange

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/AssemblyInfoFromResolveAssembly.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IncomingMessage.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageRaw.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/OutgoingMessage.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Packet.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Request.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- rename command for clarity and compliance with coding standards
- rename several fields and variables to comply with coding standards
- add class providing DebugEngine extensions
- add IsDeviceInInitializeStateAsync to DebugEngine extensions
- rework WFP test app
- rename MARKER_DEBUGGER_V1 and MARKER_PACKET_V1 to follow nanoFramework naming
- rework ResolveAssemblyAsync and ResolveAllAssembliesAsync
- remove unused flags enumeration from DebuggingResolveAssembly.Reply
=> Work on DebuggingResolveAssembly

source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- add back flags for assembly deployment status (now are Enum)
- bumped Nuget version to 0.4.0-preview010
=> Revert removal of assembly deployment flags

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DeploymentSectorExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/FlashSectorDataExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/DeploymentBlock.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/DeploymentSector.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- rework method to deploy using flash map
- add code and extension as required
- bumped Nuget version to 0.4.0-preview013
=> Work on DeploymentExecuteIncrementalAsync

source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- was missing a filter to get only the blocks available for deployment
- bump Nuget version to 0.4.0-preview015
=> Fix bug with deployment blob building

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/USB Test App WPF/packages.config, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Request.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- improve ProcessMessage so the return is never null
- improve PerformRequestAsync so the return is never null
- improve code in EraseMemoryAsync to check for bad execution
- replace timeout values with constants in EraseMemoryAsync for clarity
- fix nanoframework/nf-Visual-Studio-extension/#107
- bump Nuget version to 0.4.0-preview017
=> Fix erase memory command

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- improve code on connectAsync (was wrongly trying to disconnect devices on error which was causing a race condition)
- STLink ports are now being checked for valid nanoFramework devices behind it (to account for boards that are making use of the Virtual COM port provided by the ST Link interface)
- fixes #40
=> Improve detection of nanoFramework devices

appveyor.yml, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- minor code improvements in async calls
- bump NuGet package to 0.4.0-preview022
=> Correct method names

source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- Remove Disconnect from RebootDeviceAsync().
- Add optional parameter to GetDeviceInfoAsync() so the retrieval of the device information can be forced.
- Remove backing field of NanoFrameworkDeviceInfo.Valid.
- Bump NuGet package to 0.4.0-preview024.
- Improvements required/nice to improve deployment and debug process.
With STM32F769I target and WPF test app.
=> Improvements for deployment and reboot

appveyor.yml, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- Fixed wrong return value on SetExecutionModeAsync().
- Also fixed comment typo.
- Bump NuGet to v0.4.0-preview025.
=> Fix wrong return value on SetExecutionModeAsync

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/RebootOption.cs
- Device watchers no longer use the delayed disposed and removal approach.
- Remove `NoReconnect` option from `RebootOption` because it doesn't make sense anymore.
- Add code to forcibly disconnect the device on soft reboot to allow proper watcher workflow (isn't the case if there is an open connection).
- Current implementation of nF devices detection/connection (using device watchers) doesn't allow _reusing_ the device and the engine on device reboot because the device actually goes away and returns as a "new" one. Any reconnection mechanism required has to be implemented at the caller layer.
- Solves the critical reconnection issues that have been plaguing the debugger.
=> Rework device watcher

source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortUsb/EventHandlerForUsbDevice.cs, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Net/packages.config, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RunTimeValue.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Array.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Class.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Indirect.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_String.cs, source/nanoFramework.Tools.DebugLibrary.Shared/SRecordFile.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/ConnectionSource.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IncomingMessage.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/OutgoingMessage.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Request.cs
- Add ConfigAwait to async calls.
- Rename `ConnectionSource` enum to follow project name casing
- Add Nuget package with ConfigureAwaitChecker analyser
- Following GP on async/await patterns
=> Add ConfigAwait to async calls

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs
- Add property to signal device enumeration completed.
- Useful for upper layer to have access to this property when the corresponding event handler isn't set or the enumeration completes before the handler is actually added.
=> Exposed property to signal device enumeration completed

source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Net/packages.config, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RunTimeValue.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Array.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Class.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_Indirect.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_String.cs, source/nanoFramework.Tools.DebugLibrary.Shared/SRecordFile.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IncomingMessage.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/OutgoingMessage.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Request.cs
- Correct implementation of slim semaphores in `SendBufferAsync()`, `ReadBufferAsync()` and `PerformRequestAsync()`
- Remove ConfigureAwaitChecker Analyzer
- Global remove ConfigureAwait(false) because context is required on 99% of the code
- Correct code in SerialPort to use IsDevicesEnumerationComplete (regression)
- Rework code on `PerformRequestAsync()`
- Simplified several nested calls to remove the _repeated_ await
- Tested with WPF test app
=> Improvements with communication stability

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Remove call to Start in ConnectAsync because we need to have better control over this
- Add code to check for invalid Capabilities on ConnectAsync and failing on error
- Made Engine.Start  return Task so it can be properly used as a Task
- Improve cancellation token management in Engine.Start
- Rework code to add devices to nanoDevices collection
- Rework code to ReadBufferAsync in order to prevent throwing exceptions on errors
- Update WPF test app
- Addresses stability issues 
- Helps resolving nanoFramework/Home#247
=> Stability improvements

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
- Addresses issues that were causing unstable behaviour on device connect/disconnect
=> Fix several issue with connect/disconnect workflow

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Extract ProcessBackgroundMessages and ProcessSpuriousChars methods
- Rework Start method accordingly
- Remove unnecessary await in ReadBufferAsync
- Update test app
=> Work on Debuger Engine

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/SerialPort.cs
- Rework SerialDevice and event handlers to really reuse SerialDevice (UWP API doesn't like to open/close serial devices)
- SerialDevice DataWriter and DataReader are now local to methods that use them
- SerialDevice close doesn't dispose device watchers and event handlers anymore
- Remove unused #pragma warnigns
- Engine constructor is now internal
- ProcessIncomingMessages now tries to connect to device before starting processor
- Rework Engine constructor to remove unnecessary initializations
- NanoDevice debugger is now created on property access
- Refactor code to follow coding guidelines
- Code clean-up
- Update WPF test app
=> Rework SerialDevice and associated classes

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add code to check for null replies
- Fixes potential issue when the list of resolved assemblies has one (or more) null replies 
=> Fix issue with ResolveAllAssembliesAsync

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
- Improve adding devices after enumeration is completed
- After device enumeration was completed any new device arriving would have it's description truncated because the property changed event for the collection was fired before the description was actually updated leading to a truncated description on bound controls (such as VS extension)
=> Fix wrong device description after enumeration

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add cancellation with default timeout when creating Task to execute sync requests
- This is to make sure the sync tasks are ended after a set timeout
=> Add cancellation with default timeout

source/USB Test App WPF/Serial Test App WPF.csproj, source/USB Test App WPF/Serial Test App WPF.nugetreferenceswitcher, source/nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/ReleaseInfo.cs, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- Add CompilerInfo to SoftwareVersionProperties
- Increase size of ReleaseInfo.Info string
- Rename fields in SoftwareVersion and ReleaseInfo
- General improvements in processing of string properties comming from device
- Add Nuget package switcher to WPF test app
- Improves information from device
- Addresses nanoFramework/Home#264
- Test apps in debugger project (requires changes in interpreter code)
=> Improvements in device information

source/Debug Library/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/EventHandlerForSerialDevice.cs
Changes to allow ESP32 boards  to work with Visual Studio extension 
The original code only allowed serial ports with the name "STM32 ST LINK" to connect, this change removes this check.  
With the ESP32 boards the serial link would default to 7 bit data but 8 bit data is required. Now it is forced to 8 bit data.
Now when an ESP32 board is connected it is seen in Visual Studio.
Signed-off-by: Adrian Soundy <adriabsoundy@gmail.com>
=> Allow ESP32 boards to work with Visual studio extension

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
- Rework async and sync requests
- TaskCompletionSource now uses fixed type instead of object
- Extra check for cancelation request on serial send and receive methods
- Work on improving general stability and solve VS hanging
- WPF test app and VS experimental instance
=> Rework async and sync requests

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Remove hack in writememory
- General improvements in several methods
- Update code in test app
- Improved dispose code
- This was a hack to overcome an issue with USB packets smaller than 64 bytes at the end of the batch (not required anymore) it has to be handled at the native end. See nanoframework/nf-interpreter#596
=> Work on stability

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IControllerHost.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
- Add new field to IControllerHHost to flag if connected target implements CRC32 in Wire Protocol (headers and payload)
- Update code accordingly
- Addresses nanoFramework/Home#288
=> Implement optional CRC32 in Wire Protocol

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- On Ping return null the code would wrongly continue reporting a succesfull connection. This would cause all sorts of issues ahead based on a false information that there is a target connected.
- Fixes serious bug
=> Fix potential issue on ConnectAsync

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfigurationOption.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Add new command: Monitor_UpdateConfiguration
- Configuration Option for configuration get/update commands is now an enum DeviceConfigurationOption
- Rename WriteDeviceConfigurationAsBlock to UpdateDeviceConfigurationAsBlock
- Rework UpdateDeviceConfigurationAsBlock to use it's own command implementation instead of direct memory write. This is to accomodate targets that do not store their configuration directly in flash memory
- Update test app with the above
=> Work on config block get and update

source/nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add this new flag to the Capabilites struct
- Update UpdateDeviceConfigurationAsBlock accordingly 
This required to accommodate targets with different flavours of configuration block storage/management. Looking into this flag the engine knows if a flash erase is required before uploading the configuration block.
- Requires nanoframework/nf-interpreter#648
=> Add suport for ConfigBlockRequiresErase flag in Capabilities

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Now works when target device is running nanoBooter
(requires fw image supporting ReadMemory command in nanoBooter)
- Allows storing configuration blocks when target is running nanoBooter (previously was only possible when running nanoCLR)
=> Fix UpdateDeviceConfiguration

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
This fixes a problem which caused the ReadBufferAsync etc to get in a tight loop. Trying to read data but finding the device handle is invalid which creates an exception. The calling code will try to connect again but picks up invalid handle as it thinks it still connected then tries to do a read again.
The original problem is that LoadAsync(32) initially only returns 19 bytes when the ESP32 is rebooting after a deploy.
Because it created a buffer of 32 bytes the ReadBytes tries to read 32 bytes from stream but there are only 19 available so we get an exception, data out of range.
This never ending loop also causes the Visual Studio to not close properly and processes are left in the background using lots of CPU time.
- [] Improvement (non-breaking change that improves a feature, code or …
=> Fix problem on SerialPort  ReadBufferAsync

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/NetworkConfigurationBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/Wireless80211Base.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- The string fields weren't being properly handled
- Add constructors to config base classes to ensure that the byte arrays size match
- Minor improvements in WPF test app
- Fixes issue with storing/getting wireless config block to/from device
- WPF test app
=> Fix issues with wireless config save/load

source/USB Test App WPF/Serial Test App WPF.csproj, source/USB Test App WPF/packages.config
- Project now references debugger project instead of Nuget
=> Work on WPF test app

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Update QueryCLRCapabilities to hold a list with the native assemblies details
- Update NanoFrameworkDeviceInfo.ToString() to have a nicelly formated list of the native assemblies
- Remove GetInteropNativeAssemblies from engine
- Update WPF test app accordingly
- Working towards nanoFramework/Home#329
- WPF test app
=> Move command to list native interop assemblies to QueryCLRCapabilities

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Need to change type and constant declaration to match native execution
=> Fix Debugging_Execution_BreakpointDef

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/EventHandlerForSerialDevice.cs
- Partial rewrite on the connect device workflow
- Improvements on the disconnect device worfflow
- SerialPort now has Read and Send cancellation tokens to improve cancelling of pending I/O operations on device disconnect
- Valid nanoDevice checking after complete devices enumeration is now carried as a separate task and not part of handler anymore
- Remove unused flag for autoreconnect on serial device event handler
- DebugEngine propery in NanoDeviceBase doesn't auto-instanciate anymore
- NanoDeviceBase now has a CreateDebugEngine
- Engine doesn't offer a Disconnect method anymore
- Engine doesn's start background processor on constructor anymore becuase the associated nanoDevice might not be connected at that point, instead is started an ConnectAsync if needed
- Engine.RebootDevice …
=> Major rework on SerialDevice and Engine

source/USB Test App WPF/Serial Test App WPF.csproj, source/USB Test App WPF/packages.config, source/nanoFramework.Tools.DebugLibrary.Net/FodyWeavers.xml, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Net/packages.config, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/NetworkConfigurationPropertiesBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/Wireless80211ConfigurationPropertiesBase.cs, source/nanoFramework.Tools.DebugLibrary.UWP/FodyWeavers.xml, source/nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- Using Fody PropertyChanged package
- Implementing this allows using the component on MVVM apps making the bindings smoother
=> Add PropertyChangedInterface to device configuration classes

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Forces a minimum Memory Erase timeout.
A workaround to ensure a minimum of 10 seconds is permitted to 
any device performing a Memory Erase before a timeout will occur. 
Addresses timeout issues experienced on ESP32 devices during
debug/deploy.
=> Fix to address ESP32 Memory Erase timeout

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfigurationBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfigurationOption.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/X509CaRootBundleBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/X509CaRootBundlePropertiesBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Improve Monitor_UpdateConfiguration command to handle configuration blocks larger then the WP buffer size.
- Add new configuration block to store X509 certificates.
- Need for the configuration block API to handle configuration blocks larger than the WP buffer size e.g. storing CA root certificates.
- Test app in the solution. Correctly performed update of config block with network config and a CA certificate.
=> Work on update device config

source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/TaskExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
- Add extension to cancel task after timeout.
- Improve code to `SerialDevice.FromIdAsync` to handle execution blocking with faulty drivers and non returning calls.
- Attempt to mitigate reported issues with device discovery with Bluetooth virtual serial ports and some ESP32 serial interfaces.
=> Improve SerialDevice creation

source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs
- Improve error messages for memory and flash maps.
- Was throwing an hidden exception when trying to output line for nanoBooter on targets that don't have it.
=> Fix FlashSectorData ToString

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/SerialPort.cs
- Improve check of nanoBooter on device discovery: the code now checks for a valid marker in the received packet.
- PortBase class now has methods to Start and stop the device watchers and also to rescan devices.
- SerialPort and UsbPort now have an overloaded constructor allowing to instanciate the class without starting the device watchers.
- Update test app.
- Improves device discovery.
- Improves developer experience allowing VS to start debugger component with or without device watchers started.
- Improves developer experience allowing VS to rescan devices without forcing developer to physically unplug and plug nanoDevices that are behind a serial converter.
=> Improvements device discovery and PortBase classes

source/nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs
- .NET version was missing the new CreateInstanceForSerial constructor.
=> Update CreateInstanceForSerial constructor for .NET lib

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs
- Tweak SerialDevice dispose and closing.
- Attempt to improve SerialDevice disconnect workflow.
=> Improve disconnection of SerialDevice

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Improve output messages.
- Add missing code to report failure on retrieving device flash map.
=> Work on DeploymentExecuteIncremental

source/USB Test App WPF/MainWindow.xaml, source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add ErrorCode field to Monitor_ReadMemory.Reply class.
- Update deserializer method accordingly.
- Add enum with error codes for access memory operations.
- Rework Engine.ReadMemory() methods to add operation error code.
- Rework Engine.ReadMemory() method to improve processing of reply.
- Update test app to verify command functionality.
- ReadMemory command wasn't working properly. 
- Needed the command to be able to read BOOTLOADER and CLR regions to improve VS extension features. 
=> Work on ReadMemory command

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/DebuggerExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/version.json
- Add debug state flag: ResolutionFailed.
- Add device state extension to process this flag.
- Add code to the test app.
- Bump version to 1.1.0-preview.
- Change version config to use semver 2.
- This flag has been added to the interpreter for some time but never got any support in the debugger.
=> Add support for type resolution failed flag

source/nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/INanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/version.json
- Add these to interface.
- Rename PlatformName to Platform for clarity and to follow SystemInformation class.
- Bump version to 1.2.1-preview.
=> Work TargetName and Platform properties

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add code to update IsConnected flag on reboot command.
- Without it the device state isn't updated nor forced to upon reset.
- Fixes nanoFramework/Home#489.
=> Fix bug with connected state upon reboot

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Capabilities/Esp32.TargetCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Capabilities/Nxp.TargetCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Capabilities/Stm32.TargetCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Capabilities/TICC32xx.TargetCapabilities.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/INanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Add these to NanoFrameworkDeviceInfo and interface.
- Add target capabilites enum for all available platforms.
- Update test app with these.
- With these new data fields targets can report capabilities specific to the platform and to the target. Having them as general flags wouldn't work as that would be a waste of space because of the differences between platforms and targets. Having them generic allows for those differences and the real meaning is figured out by an upper layer. 
=> Add PlatformCapabilities and TargetCapabilities to CLRCapabilities

source/nanoFramework.Tools.DebugLibrary.Net/PortSerial/EventHandlerForSerialDevice.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.UWP/PortSerial/EventHandlerForSerialDevice.cs, source/version.json
- Update configuration for serial baud rate to 921600.
- Bump version to 1.3.0-preview.
- All current targets support this baud rate without any problem. This increases Wire Protocol throughput ~8x.
- Transport is actually performed with USB, serial is only used on very short distance on the board, meaning that no transmission issue will raise from this. Even if that's the case the WP layer has error checking mechanism that can be used to detect this, if needed.
=> Update serial baud rate to 921600

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, source/version.json
- On serial devices we are now attempting connecting with three different baud rates.
- Supported baud rates are: 921600, 460800, 115200.
- Bump version to 1.5.0-preview.
- This is to accommodate targets connected through serial with low specs that can't perform that well with high baud rates.
=> Improve serial target detection

source/nanoFramework.Tools.DebugLibrary.Shared/DebuggerEventSource.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageRaw.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/OutgoingMessage.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Packet.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequestsStore.cs, source/nanoFramework.Tools.Debugger.sln, source/version.json
- Add serializable attributes to WP classes.
- Fix declaration, locking and increase of WP output message sequencer.
- Fix CRC check of VerifyHeader.
- OutgoingMessage internal constructor was missing the sequenceId parameter.
- Improve robustness of add method on WP requests store. Could throw exception when a message with the same sequence was already on the dictionary.
- Modernize and fix trace output of WP messages.
- Bump version to 1.7.0-preview.
- Add version to solution items folder.
- Fixes several issues with WP implementation adding robustness.
- UWP test app.
=> Fixes and improvements in Wire Protocol

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/version.json
- Add new command to Debugging_Execution_QueryCLRCapabilities to query assemblies count.
- Rework DiscoveryInteropNativeAssemblies() to make use of new command and keep backwards compatibility with older targets.
- Move "magic number" with NativeAssemblyDetails struct size to a constant in the struct.
- Update code accordingly.
- Bump version to 1.7.0-preview.
- With the current implementation the assemblies listing of the target was received in a single batch. This could cause issues on targets with a large number of assemblies, because of the extra time in processing the packet through CRC32 calculation and sending a large packet over the Wire Protocol channel (can easily reach 2/3k !!).
- With a paged query of the assemblies we now respect the max packet size announced by the target …
=> Implement paged request of assemblies available in the target

source/nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs
- Add null checks to several properties.
- Improve code robustness. 
- UWP test app.
=> Improve ToString of NanoFrameworkDeviceInfo

source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, source/version.json
- On fatal communication errors the device is now forced to disconnect.
- Add try/catch on close device to catch Interop exceptions.
- Add 1 second wait for arriving devices before attempting communication.
- Remove second attempt to communicate with device.
- Remove misleading output message about device invalid base.
- Bump version to 1.9.0-preview.
- Improve device detection.
- Improve stability of the component.
- Code quality improvements.
=> Improvements in serial device detection

source/nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs
- Revert some changes and add back the second attempt to communicate with device.
- Decrease boot time to 1000ms.
- The second attempt seems to be the best way to deal with dual USB devices.
=> Revert some changes in detection workflow

source/nanoFramework.Tools.DebugLibrary.Shared/NanoDevicesEventSource.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
- Add sanity check for payload size.
- Debug output of device IDs now are striped of the GUID of COM port device interfaces and device instance index (that show in composite USB devices).
- On initial stage when the CRC23 in Wire Protocol is not active, a bad packet header could request payloads of impossible length causing out of memory exceptions. Now it's limited to twice the WP packet size.
- Improve debug output messages by removing "noise" from useless data.
=> General improvements with serial devices

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add new parameter to chose if device capabilities should be requested.
- Bump version to 1.11.0-preview.
- Needed a lighter method to "just" connect to a target and check if it is a nanoDevice. Previous implementation was always requesting all the device capabilities for nothing.
=> ConnectAsync now requests device capabilies optionally

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Fix error checking on WriteMemory operation.
- The check was wrongly using a magic value instead of an enum.
Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>
=> Fix error checking on WriteMemory operation

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, source/nanoFramework.Tools.DebugLibrary.Net/packages.lock.json, source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/version.json
- Set default value for Engine.ThrowOnCommunicationFailure to false.
- Update several NuGets.
- Rework test app regarding device execution querying.
- Bump version to 1.16.0-preview.
- Throwing so many exception was putting a high burden on the callers to trap and deal with those, thus having the potential to cause VS to freeze and exit without warning.
=> Replace several throws with return value

source/nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add new base class OverheadBase to get overhead of command to be TXed to target.
- All commands that have a buffer now derive from this new class.
- Update processing of all engine commands that use the above commands.
- Commands that use a data buffer were relying on packet length to adjust the chunk size. This is wrong because that doesn't take into account the overhead of the rest of the command thus overflowing the buffer on the target.
Now the data buffer is adjusted so that the payload doesn't exceed the wire protocol packet size.
=> Improve commands that use full WP buffer capacity

source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- For reboot requests that cause hard reboot on the targets it's very likely that the reply back is not sent. Issuing the command with a very short timeout speeds up things.
- Add else to wait for ping event to occur on soft reboot.
- Improve behaviour and execution of reboot command.
=> Add short timeout to reboot request

source/USB Test App WPF/MainWindow.xaml.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfigurationBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/WirelessAPBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/WirelessAPConfigurationPropertiesBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/Wireless80211_ConfigurationOptions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/WirelessAP_ConfigurationOptions.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, source/nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems, source/version.json
- Add support for Wireless AP configuration.
- Fix missing property in Wireless80211 configuration classes.
- Add extensions to output string from 802.11 and AP configurations.
- Update WPF test app to validate the above.
- Bump version to 1.17.0-preview.
- Add support to query/configure Wireless AP configuration blocks.
- Fix issue with Wireless 80211 config block.
- Serial test app.
=> Work on wireless configs

source/nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/PortBase.cs, source/nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, source/version.json
- Rename to Port black list to be more generic (instead of COM port specific).
- Move property to PortBase.
- Update code accordingly.
- Bump version to 1.18.0-preview.
- Improves usability and makes it more generic.
=> Rework COM port black list

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, version.json
- Now return an enum instead of an uint.
- Rework code to properly process reply from device and return correct result to caller.
- Bump version to 1.18.2-preview
- Return from these methods wasn't being properly constructed and some conditions return wrong results.
=> Fix return result for WriteMemory and EraseMemory

nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Move HasProprietaryBooter and IFUCapable flags to Ping.
- Add ConfigBlockRequiresErase to ping because this information is also required when running booter and it wasn't available there.
- Rename Ping flags field to drop "debug" hit on the name.
- Rename Ping source field to follow code style guidelines.
- These capability flags are needed on both booter and CLR so they need to be moved to a command that is present on both.
=> Work on capability flags

USB Test App WPF/MainWindow.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add code to process reply and set capability flags.
- Add code to test app to show device capabilities.
- Add obsolete attribute to deprecated enum.
=> Expose capability flags

USB Test App WPF/MainWindow.xaml, USB Test App WPF/MainWindow.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/RebootOptions.cs, version.json
- Rename nanoBooter.
- Add option to launch bootloader.
- Update test app.
- Bump version to 1.20.0-preview.
=> Update boot options

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/RebootOptions.cs
- Fix reboot options.
- Add flag attribute.
- Need to be "flag" type.
=> Fix reboot options

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add flag to Ping to expose support for nanoBooter.
- Need to improve the information about a device right from the discovery process.
=> Add flag to Ping to expose support for nanoBooter

USB Test App WPF/MainWindow.xaml, USB Test App WPF/MainWindow.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/MFDeployTool/NanoFrameworkDeviceInfo.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/TargetInfo.cs, nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems
- Expose BooterVersion anc ClrVersion as Version type properties in NanoDeviceBase.
- Deployment and CLR start address are now methods.
- Improve code in RebootTonanoBooter to become more robust to exceptions.
- Improve code in PrepareForDeployAsync to use more direct properties.
- Update code to use new command Monitor_TargetInfo.
- Improve code to make use of new exposed properties in NanoDevice.
- ConnectAsync in debugger engine now retrieves target capabilites and exposes those in a property.
- ConnectAsync in debugger engine now retrieves flash map.
- Improve ToString output of device capabilites to include new properties.
- Adds support for nanoframework/nf-interpreter#1789.
- Makes target properties more readily available.
- Test apps.
=> Add Monitor_TargetInfo command

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Increase timeout of valid nanoDevice call.
- Remove request capabilites parameter in ConnectAsync. Default is already true.
- Fix condition to get target information and flash sector map on nanoBooter connect.
- Target details weren't being retrieved on nanoBooter connect operation.
- Target detection was missing some "slow" devices because of the too short timeout.
=> Improve device detection

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs
- Add semaphore for receive operation.
- Add check for semephore WaitOne call.
- Making sure that operations don't overlap.
=> Improve serial read/receive operations

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Improve code to erase all blocks (flash sectors).
- Remove useless code.
- Simplifications by using existing properties instead of pulling them again from the device.
- EraseAsync wasn't erasing all the flash sectors in the memory block only the 1st one.
- TODO possibly rename the FlashSectorData class and friends to match the names used in native code.
=> Fix EraseAsync

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
- Made address variable common to use on request and output.
- Fixes wrong output with flash sector being erased.
=> Fix output of address on erase operation

nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, nanoFramework.Tools.DebugLibrary.Net/packages.lock.json, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/CachedDeviceInfo.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, nanoFramework.Tools.DebugLibrary.Shared/nanoFramework.Tools.DebugLibrary.Net.projitems, nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj, nanoFramework.Tools.DebugLibrary.UWP/packages.lock.json, version.json
- Add retry policies with Polly to several locations.
- Default time to perform second search is now 2 seconds.
- Revise exception processing in several locations to add resilience to device disconnection and USB comm issues.
- Add cache mechanism to shorten device detection.
- Device Description is now composed on the fly from existing properties.
- Bump version to 1.24.0-preview.
- Improve device detection workflow.
- Make lower layer methods more resilient to USB issues.
- Test apps in solution.
=> Improvements in device detection

Serial Test App UWP/MainPage.xaml.cs, USB Test App UWP/MainPage.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDevice.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/IPort.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPort.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, nanoFramework.Tools.DebugLibrary.Shared/PortUSB/UsbPort.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IControllerHostLocal.cs, version.json
- Rework SendBuffer and ReadBuffer to remove async calls and to throw DeviceNotConnectedException exception.
- Rework initial SerialDevice detection.
- Remove Async suffix from several APIs.
- Bump version to 1.25.0-preview.
- Improve stability on the communication an discovery of devices.
- Test apps in solution.
=> Work on async calls

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj
- Remove all connect and reconnect calls.
- Code clean-up.
- Simplify code and remove impossible operation of launching nanoBooter from inside the device.
=> Rework DeployFile inner methods

nanoFramework.Tools.DebugLibrary.Net/nanoFramework.Tools.DebugLibrary.Net.csproj, nanoFramework.Tools.DebugLibrary.Net/packages.lock.json, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.UWP/nanoFramework.Tools.DebugLibrary.UWP.csproj, nanoFramework.Tools.DebugLibrary.UWP/packages.lock.json
- Add Polly wait and retry policy to perform repeated attempts to connect to a device.
- Improve operation robustness and resilience to failure by taking the responsibility to retry the operation, instead of being the client app.
=> Add attempts parameter to ConnectAsync

USB Test App WPF/MainWindow.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/Extensions/FlashSectorDataExtensions.cs, nanoFramework.Tools.DebugLibrary.Shared/Extensions/MonitorFlashSectorMapExtensions.cs, nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/DeploymentBlock.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, version.json
- Rename struct vars.
- Add new constants to allow processing Block Region Attributes.
- Rework DeploymentBlock to add support for ProgramAligment field.
- Rework WriteMemory to process program alignment attribute on flash map.
- Rework test app to test new feature.
- Bump version to 1.27.0-preview.
- Need to address specificity of STM32L4 flash programming.
- Following nanoframework/nf-interpreter#1815.
- Test app and new STM32L4 target.
=> Work Flash Sector Data

USB Test App WPF/MainWindow.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Code has been optimized to prevent duplicated and needless calls to device ping.
- GetConnectionSource now also updates the ConnectionSource field.
- Update test app.
- Improve erase operation efficiency.
=> Improvements in EraseAsync

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/SerialPortManager.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add new property IsConnectedTonanoBooter.
- Add backing field.
- Rework code to use either the internal field or the properties directly.
- Marked as obsolete.
- Improve access to device information through debug engine properties.
=> Rework ConnectionSource property

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Switch to TargetInfo because Capabilities is only available when runnign CLR.
- 
- Operation wasn't possible when target was running nanoBooter.
=> Fix access to platform name

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Remove this on ConnectAsync and update debugger flags.
- This is not required for properly launch a debug session. Actually it prevents exceptions thrown at early stages of boot sequence to be showned on VS output window.
=> StopDebuggerOnConnect shouldn't resume execution

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
Logic was using DateTime.MaxValue which could establish a value that is later adjusted for time zone.  DateTimeOffset.MaxValue is already set to UTC which is the default for DateTimeOffset.
Additional problem was in Engine.cs - there are a couple of of commands that are used in the test harness that need to be declared as public so they can be tested.
Added some comments in PortSerialManager.cs about the possibility of eating non-serial problems in the try/catch block.
Fix #742
1.   Initialized Expires with DateTimeOffset.MaxValue instead of DateTime.MaxValue
2. Changed two interfaces to public to allow testing with the test harness that is in the repo
3. Documented via comment that the open catch in the try/catch could hide programming mistakes
- Fixes nanoFramework/Home#742
Tested using …
=> Fix initialization of Expires in WP Request

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IController.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IControllerHost.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
- Rework LastActivity in controllers and engine.
- It's now updated on MessageReassembler.
- Add new method IsIdle.
- PerformRequest now waits for controller to be idle before sending the packet.
- Addresses nanoFramework/Home#755
=> Improve WP request send

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
- Return now depends on the operation success.
=> Fix set execution

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Erase memory doesn't ping device anymore (no need to find if it's responsive).
- Detection clears buffers to make sure there is nothing preventing a correct communication with the device.
- No need to force connect on detection.
- Setting execution flags now has a delay of 500ms before returning to allow the target to settle with the new conditions.
- Improves device detection and communication workflow.
=> General improvements

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Packet size algorithm was failing to handle packet size smaller than the program aliment size.
- Change default timeout for write memory to twice the default timeout.
- When buffer size had the last chunk of data smaller than the program alignment size, this ended on a endless loop wrongly sending a zero sized packet to wrap up the operation.
- For packets of a large size in MCUs that have long flash write times, this could result on timeout errors causing the operation to fail.
=> Fix packet size for targets requiring program alignment

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs
Extended `GetPortNames()` to support UNIX (Linux/OSX/FreeBSD) runtime environments:
-  Added `GetPortNames_Linux()`.
-  Added `GetPortNames_OSX()`.
-  Added `GetPortNames_FreeBSD()`.
-  Unchanged `GetPortNames_Windows()`.
When testing a deployment using Mono on macOS, the DeviceEnumeration never completed which is because nf-debugger is only supported on Windows. This change adds support for devices connected on UNIX machines.
Tested successfully on macOS to erase & flash a device using nf-debugger:
=> Add UNIX support for PortSerial

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs
Improved Linux SerialPort lookup to have better support for devices connected on /dev/ttyUSB, /dev/ttyACM and /dev/ttyAMA.
When trying to enumerate the devices on Raspbian, the device was available under /dev/ttyUSB0 but previously these ports were never scanned because it was only scanning /dev/ttyGS and /dev/ttyS.
=> Improved Linux SerialPort lookup

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add timeout to Task wait on sync requests.
- When there are problems executing the sync request, the task has the potential to hang or loop. Adding a timeout here, with the same value as the command takes care of this.
=> Add timeout to PerformSyncRequest

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/IControllerHostLocal.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/MessageReassembler.cs
- Add code to process bad header and bad payload.
- Add implementation to report this back to the device.
- Support in device WP processor implemented with nanoframework/nf-interpreter#2162.
- Allow WP state machine to receive reply on bad packet/payload instead of relying on timeout to move forward.
=> Add processing for bad WP packets

nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortComposite/PortCompositeDeviceManager.cs
- Add parameter to network port managers to control watchers.
- The network ports where missing this parameter which was causing issues when being used in VS and with the composite port, because the start operations where overlapping as they run on different threads.
=> Add parameter to network port managers to control watchers

nanoFramework.Tools.DebugLibrary.Shared/PortTcpIp/NetworkWatcher.cs
- Rework start code for UdpClient to allow several instances listening on the same port.
- Rework listener thread to allow graceful stopping.
- Allow several instances listening on the same port. Required for multiple VS instances running.
- Stopping the watcher was causing exceptions and/or causing the socket to actually remain opened.
- VS experimental instance.
=> Fix network watcher

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Controller.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs
- Remove sleep when performing WP requests.
- Add new property IdleThreshold to WP controller.
- With the latest improvements in WP it doesn't seem to be needed anymore this workaround to improve communication reliability.
=> Remove idle check from WP requests

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequest.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/WireProtocolRequestsStore.cs, version.json
- PerformSyncRequest now use the same code.
- Replace lock with SemaphoreSlim.
- WireProtocolRequestsStore doesn't have timer to clean-up requests anymore.
- Requests are removed from store on Task.WaitAll failed.
- WireProtocolRequest now stores itself on TaskCompletionSource state.
- Tiny improvements in code from analysers.
- Bump version to 2.2.0-preview.
- Following DRY principle.
- Improving code redability.
- Improving communication with nanoDevices.
=> Rework PerformSyncRequest

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/Runtime/RuntimeValue_String.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Simplification of return, now uses AccessMemoryErrorCodes enum.
- Rework code accordingly.
- Sprinkle artificial thread sleeps to allow some slack in the channel.
- Add extra timeout in write operation.
- Rename and simplify PerformWriteMemoryCheck.
- Minor tweaks from analyser warnings and suggestions.
- Improvements in deployment.
=> Improve WriteMemory

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- These flags where never used as they are in the WP Monitor group.
=> Remove unused flags of QueryCLRCapabilities

nanoFramework.Tools.DebugLibrary.Shared/CLRCapabilities.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Add flag.
- Add property exposing it.
- Exposes improvements from nanoframework/nf-interpreter#2277.
=> Add CanChangeMacAddress to CLR capabilites

nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/DeviceConfiguration.cs, nanoFramework.Tools.DebugLibrary.Shared/DeviceConfiguration/NetworkConfigurationBase.cs
- Byte arrays for IPv6 structs weren't being created in constructor.
- Serialization of IPv6 addresses wasn't correct.
=> Fix network configuration serialization

USB Test App WPF/MainWindow.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Method now returns an enum with detailed outcome of the operation.
- Add sanity checks to detect invalid base configuration in the target.
- Fix erase of configuration region (now erases all config blocks instead of just the 1st one).
- Add Sleep between operation and retries to give a break to WP processor.
- Rework code to return proper report of failure/success.
- Test app.
=> Improve UpdateDeviceConfiguration

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerialManager.cs
- Added lock, that guards increment and decrement of `_newDevicesCount`
- Fixes nanoFramework/Home#1017
=> Fix race condition in PortSerialManager

nanoFramework.Tools.DebugLibrary.Shared/Extensions/FlashSectorDataExtensions.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
Based on the bit flags set in the BlockRegionAttribute, send data to be flashed as a multiple of 1,8,128 or 256 bits.
Previously only 1 and 8 were supported.
To support STM32H7 series that have 128 and 256 bit minimum flash word writes.
- Corresponding flags added in native code: nanoframework/nf-interpreter#2405
Tested on STM32H735g-DK development board for 256 bits.
1, and 8 bit words should remain unaffected.
None
=> Add support for flash alignment of 128 and 256 bits

nanoFramework.Tools.DebugLibrary.Shared/Extensions/OutputExtensions.cs
- Add check for existence of CODE region.
- This was failing when the device didn't have CODE region, which can happen for RAM based devices on which all assemblies are loaded dynamically.
- Test app and virtual nanoDevice.
=> Fix output of flash table

nanoFramework.Tools.DebugLibrary.Shared/Extensions/FlashSectorDataExtensions.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Support for large flash minimum programming sizes ( e.g. Raspberry PI PICO RP2040, 2048 bits)
- Also added 512,1024 bits for future use maintaining the bit pattern.
- Following nanoframework/nf-interpreter#2505.
- Required for RP2040 
Working on PICO
=> Add support for more program widths

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/DeviceWatcher.cs
Excluding Bluetooth serial ports from the list on Mac OS. Once open, Bluetooth ports do not properly time out and the code is blocked on device detection. Creates issues with other regular ports once open as well.
- Should drastically improve device detection on Mac OS
Need deeper tests with deployer.
=> Excluding Bluetooth serial ports from the list on Mac OS

nanoFramework.Tools.DebugLibrary.Net/PortDefinitions/PortBase.cs
- Add new constructors to PortBase.
- Tidy up code following code style.
- Need to have some simple constructor options.
=> Add new constructors to PortBase

nanoFramework.Tools.DebugLibrary.Shared/PortSerial/PortSerial.cs
Fixing serial read on M1 and when partial read is provided only
- This should fix the issue in most cases of data ready to read provided before all the data are avaialbe. this will now read up to the point there is no more data available.
- This was mainly happening on M1 and it also depends of the quality of the drivers
=> Fixing serial read on M1 and when only partial data is available

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Add new enum to control this option.
- Need to provide the option to disable detailed stack trace crawling and reporting. This allows more clean output during debug if the developer chooses to not see exception messages.
=> Add flag to disable stack trace crawling on exceptions

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add NoStackTraceInExceptions property to Engine.
- UpdateDebugFlags now takes this property when setting execution mode.
=> Add NoStackTraceInExceptions property to Engine

nanoFramework.Tools.DebugLibrary.Shared/BitStream.cs
- Add check for source array length and adjusting if needed.
- Processing partial packets were causing exceptions when trying to copy a full-length array despite there wasn't enough elements.
=> Fix BitStream Buffer constructor

nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs
- Getter for Overhead property is now calculated as requested to allow accounting for properties set after the constructor is called.
- The existing implementation failed to take into account lenght of properties added after the constructor is called.
- Test application.
=> Rework OverheadBase class

USB Test App WPF/MainWindow.xaml, USB Test App WPF/MainWindow.xaml.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Commands.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
- Add Storage Operation Command
- AddFile and RemoveFile support
- Split the byte array to save as a file in chunks internally and pass it to the device
- Added 2 buttons to add and remove a file in the WPF test application
- Allow to perform operations in target storage to allow storing and deleting files from VS and/or nanoff.
On a real ESP32 device
=> Add Storage Operation Command

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/GlobalExclusiveDeviceAccess.cs
Fix to prevent exceptions on Unix. This is the quick fix. The result is that GlobalExclusiveDeviceAccess is only global (inter-process) on the Windows OS (both .NET-for-windows and .NET in WSL). On other platforms it is only exclusive within  a process (same as `lock () { }`).
When working on the original PR, I've looked for a cross-platform alternative for Semaphore but I couldn't find one out o the box. Suggestions on the internet are to use named pipes or create something based on temporary files. The latter is probably the easiest, I've done something like that before. It may not be a lot of work, but... I can't test the code on anything else than Windows.
The use of a named Semaphore in GlobalExclusiveDeviceAccess results in exceptions on Unix.
I can't test this on anything else than …
=> Fix to restore Unix-compatibility

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs, nanoFramework.Tools.DebugLibrary.Shared/PortDefinitions/PortBase.cs
- NanoDeviceBase.DeviceInfo property can be assigned from a derived class
- PortBase.IsDevicesEnumerationComplete made virtual
- PortBase.NanoFrameworkDevices made virtual
I'm refactoring my new test framework code, in preparation for the creation of PRs. To test some of the code, it is necessary to have control in unit tests over the available nanoDevices. The discovery of devices and information about devices is done via class derived from PortBase and NanoDeviceBase. The unit tests would need to implement mocks for these abstract classes. In the current version of the library it is not possible to set the three properties mentioned above. In my current version of the test framework, I'm using mockable wrappers for NanoDevice en NanoFrameworkDevices to work around that. But with three …
=> Allow PortBase and NanoDeviceBase to be used in mocks

nanoFramework.Tools.DebugLibrary.Shared/NFDevice/NanoDeviceBase.cs
* NanoDeviceBase.CLRVersion made virtual
Missed this one in the previous PR, didn't notice it cannot be assigned like the other properties. Same story: in a mock of NanoDeviceBase you would want to specify the firmware version, to check whether it is the version required for the project.
=> NanoDeviceBase.CLRVersion made virtual

nanoFramework.Tools.DebugLibrary.Shared/NetworkInformation/NetworkInterfaceType.cs, nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs
Fixing configuration block deployment and Wireless AP Network type
- Fixing configuration block deployment and Wireless AP Network type
- Resolves nanoframework/Home#1593.
On a real ESP32S3 device with the nf-interperter fix nanoframework/nf-interpreter/pull/3077.
=> Fixing configuration block deployment and Wireless AP Network type
